version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker build -t 732548001766.dkr.ecr.us-east-1.amazonaws.com/temeker-bot:`$CODEBUILD_SOURCE_VERSION` . 
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 732548001766.dkr.ecr.us-east-1.amazonaws.com/temeker-bot:`$CODEBUILD_SOURCE_VERSION` 
