version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker build -t 732548001766.dkr.ecr.us-east-1.amazonaws.com/temeker:prod -t 732548001766.dkr.ecr.us-east-1.amazonaws.com/temeker:`$CODEBUILD_SOURCE_VERSION` . 
      - echo Build completed on `date`
      - docker push 732548001766.dkr.ecr.us-east-1.amazonaws.com/temeker-bot:prod 
  post_build:
    commands:
      - echo "Restarting ecs service"
      - aws ecs update-service --force-new-deployment --service temeker  
